org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
dev.steenbakker.mobile_scanner.useUnbundled=true
org.gradle.warning.mode=all
android.builder.sdkDownload=false
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64